[versions]
aboutLibraries = "10.4.0"
androidGradlePlugin = "7.2.2"
compose = "1.2.0"
composeCompiler = "1.3.0-rc02"
coroutines = "1.6.4"
detekt = "1.21.0"
koin = "3.2.0"
kotlin = "1.7.10"
ksp = "1.7.10-1.0.6"
junit5 = "5.9.0"
room = "2.4.3"

[libraries]
aboutLibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutLibraries-gradlePlugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutLibraries" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
android-material = { module = "com.google.android.material:material", version = "1.6.1" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.2" }
# Remove when AS Dolphin will be available
androidx-poolingContainer = { module = "androidx.customview:customview-poolingcontainer", version = "1.0.0" }
androidx-test-core = { module = "androidx.test:core-ktx", version = "1.4.0" }

assertK = { module = "com.willowtreeapps.assertk:assertk-jvm", version = "0.25" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.5.1" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.5.1" }
compose-uiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines"}

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# Version 1.2.0 requires AGP 7.3.0 or later
desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.6" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

junit4-api = { module = "junit:junit" , version = "4.13.2" }
junit4-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "junit5" }

junit5-gradlePlugin = { module = "de.mannodermaus.gradle.plugins:android-junit5", version = "1.8.2.1" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }

mockk = { module = "io.mockk:mockk", version = "1.12.5" }

robolectric = { module = "org.robolectric:robolectric", version = "4.8.1" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref ="room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

[bundles]
koin = [
    "koin-core",
    "koin-android"
]
compose = [
    "androidx-poolingContainer",
    "compose-compiler",
    "compose-ui",
    "compose-tooling",
    "compose-foundation",
    "compose-material",
    "compose-activity",
    "compose-livedata",
    "compose-lifecycle"
]

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version = "1.14.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersionsFilter = { id = "se.ascp.gradle.gradle-versions-filter", version = "0.1.16" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
moduleGraphAssert = { id = "com.jraska.module.graph.assertion", version = "2.2.0" }
papparazzi = { id = "app.cash.paparazzi", version = "1.0.0" }
