[versions]
compose = "1.0.4"
koin = "3.1.2"
kotlin = "1.5.31"
junit5 = "5.8.1"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version = "7.0.3" }
android-core = { module = "androidx.core:core-ktx", version = "1.5.0" }
android-appcompat = { module = "androidx.appcompat:appcompat", version = "1.3.1" }
android-material = { module = "com.google.android.material:material", version = "1.4.0" }
android-startup = { module = "androidx.startup:startup-runtime", version = "1.1.0" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.3.1" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

junit5-gradlePlugin = { module = "de.mannodermaus.gradle.plugins:android-junit5", version = "1.8.0.0" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }

[bundles]
koin = [
    "koin-core",
    "koin-android"
]
compose = [
    "compose-ui",
    "compose-tooling",
    "compose-foundation",
    "compose-material",
    "compose-activity"
]

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version = "1.13.5" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.18.1" }
gradleVersionsFilter = { id = "se.ascp.gradle.gradle-versions-filter", version = "0.1.10" }
moduleGraphAssert = { id = "com.jraska.module.graph.assertion", version = "1.6.0"}
