[versions]
koin = "3.1.2"

[libraries]
android-core = { module = "androidx.core:core-ktx", version = "1.5.0" }
android-appcompat = { module = "androidx.appcompat:appcompat", version = "1.3.0" }
android-material = { module = "com.google.android.material:material", version = "1.3.0" }
android-startup = { module = "androidx.startup:startup-runtime", version = "1.0.0" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

[bundles]
koin = ["koin-core", "koin-android"]
