[versions]
aboutLibraries = "10.1.0"
androidGradlePlugin = "7.1.3"
compose = "1.1.1"
coroutines = "1.6.1"
detekt = "1.20.0"
koin = "3.1.6"
kotlin = "1.6.10"
ksp = "1.6.10-1.0.4"
junit5 = "5.8.2"
room = "2.4.2"

[libraries]
aboutLibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutLibraries-gradlePlugin = { module = "com.mikepenz.aboutlibraries.plugin:aboutlibraries-plugin", version.ref = "aboutLibraries" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
android-core = { module = "androidx.core:core-ktx", version = "1.5.0" }
android-appcompat = { module = "androidx.appcompat:appcompat", version = "1.4.1" }
android-material = { module = "com.google.android.material:material", version = "1.5.0" }

compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version = "1.4.0" }
compose-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "compose" }
compose-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version = "2.4.1" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.5" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

junit5-gradlePlugin = { module = "de.mannodermaus.gradle.plugins:android-junit5", version = "1.8.1.0" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit5-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit5" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref ="room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

[bundles]
koin = [
    "koin-core",
    "koin-android"
]
compose = [
    "compose-ui",
    "compose-tooling",
    "compose-foundation",
    "compose-material",
    "compose-activity",
    "compose-livedata",
    "compose-lifecycle"
]

[plugins]
axion = { id = "pl.allegro.tech.build.axion-release", version = "1.13.6" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
gradleVersionsFilter = { id = "se.ascp.gradle.gradle-versions-filter", version = "0.1.13" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
moduleGraphAssert = { id = "com.jraska.module.graph.assertion", version = "2.2.0"}
