name: "build debug app"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - uses: gradle/wrapper-validation-action@v1

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check
          cache-disabled: true

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
          cache-disabled: true
