name: "Run UI tests"
on: workflow_dispatch
jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Init Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run UI tests (Android 8)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedCheck

      - name: Run UI tests (Android 10)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
